config/routes.rb
Rails.application.routes.draw do
  get 'tool/show'
  get 'tool/create'
  get 'tool/edit'
  get 'tool/update'
  get 'tool/destroy'
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def show
    @Tool = Tools.all
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/views/application/_menu.html.erb
<%= link_to 'Hello', say_hello_path %>
<%= link_to 'Bye', say_goodbye_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'application/menu' %>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>

<%= @time %>

app/views/say/hello.html.erb
<h1>Hello</h1>

<p><%= @time %></p>

<p><%= 1.hour.from_now.localtime %></p>

<% @files.each do |file| %>
    <%= file %><br>
<% end %>

app/views/tool/create.html.erb
<h1>Tool#create</h1>
<p>Find me in app/views/tool/create.html.erb</p>

app/views/tool/destroy.html.erb
<h1>Tool#destroy</h1>
<p>Find me in app/views/tool/destroy.html.erb</p>

app/views/tool/edit.html.erb
<h1>Tool#edit</h1>
<p>Find me in app/views/tool/edit.html.erb</p>

app/views/tool/show.html.erb
<h1>Tool#show</h1>
<p>Find me in app/views/tool/show.html.erb</p>

app/views/tool/update.html.erb
<h1>Tool#update</h1>
<p>Find me in app/views/tool/update.html.erb</p>